spring:
  datasource:
    url : jdbc:mysql://localhost:3306/sell?useSSL=false&serverTimezone=Asia/Shanghai
    username : root
    password : 123123
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa :
    show-sql : true
    hibernate.ddl-auto : update
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
#    password: 123123



server:
  servlet:
    context-path: /sell
wechat:
  mpAppId: wx085eb4af1c030dec
  mpAppSecret: 3a74128e7d9992e7a6d79871de24a23b
  openAppId: wx277996c4d2772104
  openAppSecret: b5e4052a545c997a6f98fe0579860bd1
  mchId: 1559874731
  mchKey: c6f1cd4bd503a7b394c28aaadef7c337
  keyPath: D:\桌面\WeChatPay\WeChatPay\1559874731_20200328_cert\h5.p12
  notifyUrl: http://zbh123.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ
#  mchId: 1409146202
#  mchKey: c976503d34ca432c601361f969fd8d85
#  keyPath: /var/weixin_cert/h5.p12


projectUrl:
  wechatMpAuthorize: http://zbh123.natapp1.cc
  wechatOpenAuthorize: http://testdev.tunnel.qydev.com
  sell: http://zbh123.natapp1.cc
logging:
  level:
   com.example.sell_master.dataobject.mapper: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml
